version: '3.4'

services:
  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Notes.Api/Dockerfile
    depends_on: 
            - database
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: SqlServer
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "!1PasswordBackEnd."
        MSSQL_PID: "Developer"
    ports:
        - "1433:1433"
    hostname: backdb-container